In [11]:
import torch

In [12]:
# 生成从0到9的整数序列
torch.arange(10)
# 输出：tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 生成从0到9的浮点数序列
torch.arange(10, dtype=torch.float32)
# 输出：tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
# 生成从0到9的整数序列，步长为2
torch.arange(0, 10, 2)
# 输出：tensor([0, 2, 4, 6, 8])

tensor([0, 2, 4, 6, 8])

In [15]:
# 生成从0到1的浮点数序列，步长为0.2
torch.arange(0, 1, 0.2)
# 输出：tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000])

In [16]:
# 生成一个浮点数序列，指定数据类型为float32，并在GPU上创建（如果可用）
torch.arange(0, 5, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [17]:
torch.arange(start=0, end=7, step=2).reshape(-1, 2)

tensor([[0, 2],
        [4, 6]])