In [1]:
import torch

# 0维张量（标量）
scalar = torch.tensor(5)
print("0维张量:")
print(scalar)
print("维度数量:", scalar.dim())  # 输出: 0
print("形状:", scalar.shape)      # 输出: torch.Size([])
print()

# 1维张量（向量）
vector = torch.tensor([1, 2, 3])
print("1维张量:")
print(vector)
print("维度数量:", vector.dim())  # 输出: 1
print("形状:", vector.shape)      # 输出: torch.Size([3])
print()

# 2维张量（矩阵）
matrix = torch.tensor([[1, 2], [3, 4]])
print("2维张量:")
print(matrix)
print("维度数量:", matrix.dim())  # 输出: 2
print("形状:", matrix.shape)      # 输出: torch.Size([2, 2])
print()

# 3维张量
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3维张量:")
print(tensor_3d)
print("维度数量:", tensor_3d.dim())  # 输出: 3
print("形状:", tensor_3d.shape)      # 输出: torch.Size([2, 2, 2])
print()

# 获取和修改张量的形状
print("获取和修改张量的形状:")
print("原始形状:", vector.shape)  # torch.Size([3])
print("增加一个维度:", vector.unsqueeze(0).shape)  # torch.Size([1, 3])
print("增加一个维度:", vector.unsqueeze(1).shape)  # torch.Size([3, 1])
print("减少一个维度:", tensor_3d.squeeze().shape)  # 如果有单一维度则减少
print()

# 拼接张量
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
print("拼接张量:")
print(torch.cat((tensor_a, tensor_b), dim=0))  # 输出: tensor([1, 2, 3, 4, 5, 6])

# 矩阵乘法
print("矩阵乘法:")
print(torch.matmul(vector, vector))  # 输出: tensor(14)  (1*1 + 2*2 + 3*3 = 14)

0维张量:
tensor(5)
维度数量: 0
形状: torch.Size([])

1维张量:
tensor([1, 2, 3])
维度数量: 1
形状: torch.Size([3])

2维张量:
tensor([[1, 2],
        [3, 4]])
维度数量: 2
形状: torch.Size([2, 2])

3维张量:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
维度数量: 3
形状: torch.Size([2, 2, 2])

获取和修改张量的形状:
原始形状: torch.Size([3])
增加一个维度: torch.Size([1, 3])
增加一个维度: torch.Size([3, 1])
减少一个维度: torch.Size([2, 2, 2])

拼接张量:
tensor([1, 2, 3, 4, 5, 6])
矩阵乘法:
tensor(14)
