In [2]:
import torch

In [8]:
a = torch.tensor([1, 2, 3])
print(a.unsqueeze(0))
print(a.unsqueeze(0))

tensor([[1, 2, 3]])
tensor([[1, 2, 3]])


In [ ]:
b = torch.rand(1, 1, 3)
print(b)
print(b.squeeze(0))
print(b.squeeze(1))

tensor([[[0.2994, 0.8627, 0.2788]]])
tensor([[0.2994, 0.8627, 0.2788]])
tensor([[0.2994, 0.8627, 0.2788]])
tensor([[[0.2994, 0.8627, 0.2788]]])


In [22]:
c = torch.rand(1, 1, 1, 1, 1, 3)
print(c)
print(c.squeeze(0))
print(c.squeeze()) # 去除所有大小为 1 的维度

tensor([[[[[[0.9984, 0.4832, 0.2856]]]]]])
tensor([[[[[0.9984, 0.4832, 0.2856]]]]])
tensor([0.9984, 0.4832, 0.2856])


In [23]:
print(c.squeeze(0))
print(c.squeeze(0).squeeze(0))
print(c.squeeze(0).squeeze(0).squeeze(0))

tensor([[[[[0.9984, 0.4832, 0.2856]]]]])
tensor([[[[0.9984, 0.4832, 0.2856]]]])
tensor([[[0.9984, 0.4832, 0.2856]]])


In [24]:
d = torch.rand(2, 2, 3)
print(d)
print(d.squeeze(0))
print(d.squeeze())

tensor([[[0.4533, 0.9540, 0.6769],
         [0.7521, 0.8787, 0.6806]],

        [[0.2324, 0.7212, 0.0102],
         [0.3809, 0.6620, 0.7068]]])
tensor([[[0.4533, 0.9540, 0.6769],
         [0.7521, 0.8787, 0.6806]],

        [[0.2324, 0.7212, 0.0102],
         [0.3809, 0.6620, 0.7068]]])
tensor([[[0.4533, 0.9540, 0.6769],
         [0.7521, 0.8787, 0.6806]],

        [[0.2324, 0.7212, 0.0102],
         [0.3809, 0.6620, 0.7068]]])


In [26]:
e = torch.rand(1, 3)
print(e)
print(e.unsqueeze(0))

tensor([[0.7867, 0.9263, 0.0946]])
tensor([[[0.7867, 0.9263, 0.0946]]])


In [3]:
# 创建一个三维张量
x = torch.tensor([[[1], [2], [3]]])
print("Original shape:", x.shape)  # 输出：torch.Size([1, 3, 1])
print("Original tensor:\n", x)

Original shape: torch.Size([1, 3, 1])
Original tensor:
 tensor([[[1],
         [2],
         [3]]])


In [4]:
# 去除所有大小为 1 的维度
x_squeezed = torch.squeeze(x)
print("Squeezed shape:", x_squeezed.shape)  # 输出：torch.Size([3])
print("Squeezed tensor:\n", x_squeezed)

Squeezed shape: torch.Size([3])
Squeezed tensor:
 tensor([1, 2, 3])


In [5]:
# 指定去除维度
x_squeezed = torch.squeeze(x, dim=0)
print("Squeezed shape:", x_squeezed.shape)  # 输出：torch.Size([3, 1])
print("Squeezed tensor:\n", x_squeezed)

Squeezed shape: torch.Size([3, 1])
Squeezed tensor:
 tensor([[1],
        [2],
        [3]])
