In [3]:
import torch

# 创建一个三维张量
x = torch.tensor([[[1], [2], [3]]])
print("Original shape:", x.shape)  # 输出：torch.Size([1, 3, 1])
print("Original tensor:\n", x)

# 去除所有大小为 1 的维度
x_squeezed = torch.squeeze(x)
print("Squeezed shape:", x_squeezed.shape)  # 输出：torch.Size([3])
print("Squeezed tensor:\n", x_squeezed)

# 指定去除维度
x_squeezed = torch.squeeze(x, dim=0)
print("Squeezed shape:", x_squeezed.shape)  # 输出：torch.Size([3, 1])
print("Squeezed tensor:\n", x_squeezed)

Original shape: torch.Size([1, 3, 1])
Original tensor:
 tensor([[[1],
         [2],
         [3]]])
Squeezed shape: torch.Size([3])
Squeezed tensor:
 tensor([1, 2, 3])
Squeezed shape: torch.Size([3, 1])
Squeezed tensor:
 tensor([[1],
        [2],
        [3]])
