In [1]:
import torch

## 2.3.1 Scalars 标量

## 2.3.2 Vectors 向量

## 2.3.3. Matrices 矩阵

In [2]:
A = torch.arange(6).reshape(2, 3)
A

tensor([[0, 1, 2],
        [3, 4, 5]])

In [3]:
# flip the axes 翻转坐标轴，也就是矩阵的转置
A.t()

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [4]:
A.T

tensor([[0, 3],
        [1, 4],
        [2, 5]])

## 2.3.4 Tensors

In [5]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.5. Basic Properties of Tensor Arithmetic 张量运算基础

In [6]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
C = torch.arange(6, dtype=torch.int32).reshape(2, 3) # int的默认数据格式是int64，当显式创建为int32时，就会特意标注dtype
D = torch.arange(6).reshape(2, 3)
A, A + B, C, D

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[0, 1, 2],
         [3, 4, 5]], dtype=torch.int32),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [7]:
D.dtype

torch.int64

In [8]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [12]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 2.3.6 Reduction 降维

In [39]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
x.sum(axis = 0)

tensor([12., 15., 18., 21.])

In [21]:
x.sum(axis = 1)

tensor([ 6., 22., 38.])

In [22]:
x.sum()

tensor(66.)

In [23]:
x.sum(axis = 0)

tensor([12., 15., 18., 21.])

In [24]:
x = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
x

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [25]:
x.sum(axis = 2)

tensor([[ 6., 22., 38.],
        [54., 70., 86.]])

In [29]:
x.sum(axis=[0, 1, 2]) == x.sum()

tensor(True)

x.sum(axis=[0, 1]) == x.sum(axis = 1)

In [44]:
y = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
y

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [45]:
y.mean()

tensor(11.5000)

In [46]:
y.sum() / y.numel()

tensor(11.5000)

In [47]:
y.mean(axis = 1)

tensor([[ 4.,  5.,  6.,  7.],
        [16., 17., 18., 19.]])

In [48]:
y.mean(axis = 2)

tensor([[ 1.5000,  5.5000,  9.5000],
        [13.5000, 17.5000, 21.5000]])

## 2.3.7 Non-Reduction Sum 非降维求和

In [51]:
z = torch.arange(24).reshape(2, 3, 4)
z

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [52]:
z.sum(axis=1, keepdims=True)

tensor([[[12, 15, 18, 21]],

        [[48, 51, 54, 57]]])

In [54]:
# 创建一个 3x4 的张量
x = torch.arange(12).reshape(3, 4)
print("原始张量 x:")
print(x)
print("x 的形状:", x.shape)

# 沿着第 0 维度（行）求和，不使用 keepdims
sum_without_keepdims = torch.sum(x, dim=0)
print("\n沿行求和，不使用 keepdims:")
print(sum_without_keepdims)
print("结果形状:", sum_without_keepdims.shape)

# 沿着第 0 维度（行）求和，使用 keepdims
sum_with_keepdims = torch.sum(x, dim=0, keepdim=True)
print("\n沿行求和，使用 keepdims:")
print(sum_with_keepdims)
print("结果形状:", sum_with_keepdims.shape)

# 演示广播机制
print("\n使用 keepdims 的结果可以直接与原张量操作:")
print(x - sum_with_keepdims)

# 尝试直接用不带 keepdims 的结果进行操作
try:
    print(x - sum_without_keepdims)
except RuntimeError as e:
    print("错误:", str(e))

# 解决方案：手动增加维度
print("\n不使用 keepdims 时，需要手动增加维度:")
print(x - sum_without_keepdims.unsqueeze(0))

原始张量 x:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x 的形状: torch.Size([3, 4])

沿行求和，不使用 keepdims:
tensor([12, 15, 18, 21])
结果形状: torch.Size([4])

沿行求和，使用 keepdims:
tensor([[12, 15, 18, 21]])
结果形状: torch.Size([1, 4])

使用 keepdims 的结果可以直接与原张量操作:
tensor([[-12, -14, -16, -18],
        [ -8, -10, -12, -14],
        [ -4,  -6,  -8, -10]])
tensor([[-12, -14, -16, -18],
        [ -8, -10, -12, -14],
        [ -4,  -6,  -8, -10]])

不使用 keepdims 时，需要手动增加维度:
tensor([[-12, -14, -16, -18],
        [ -8, -10, -12, -14],
        [ -4,  -6,  -8, -10]])


## 2.3.8 Dot Products 点积

In [75]:
A = torch.tensor([[1, 2], 
                  [3, 4]])
B = torch.tensor([[5, 6], 
                  [7, 8]])

v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

A, B, v1, v2

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]),
 tensor([1, 2]),
 tensor([3, 4]))

In [76]:
# 1. 矩阵乘法
A @ B  # 或使用 torch.matmul(A, B)

tensor([[19, 22],
        [43, 50]])

In [77]:
# 2. 点乘（逐元素乘法）
A * B

tensor([[ 5, 12],
        [21, 32]])

In [78]:
# 3. 向量点积
print(torch.dot(v1, v2))

tensor(11)


## 2.3.9 Matrix–Vector Products 

In [81]:
# 4. 矩阵和向量的乘法
A @ v1  # 或使用 torch.matmul(A, v1)

tensor([ 5, 11])

In [80]:
# 5. 外积
torch.outer(v1, v2)

tensor([[3, 4],
        [6, 8]])

## 2.3.10 Matrix–Matrix Multiplication

## 2.3.11 Norms 范数

In [83]:
# L2 范数 欧氏距离（平方和开根号）
v = torch.tensor([3.0, 4.0])
torch.norm(v)

tensor(5.)

In [84]:
# L1范数 非零元素的绝对值之和
torch.abs(v).sum()

tensor(7.)