In [23]:
import torch

In [24]:
# 3维张量
X = torch.arange(24).reshape(2, 3, 4)
print("Original shape:", X.shape)  # 输出：torch.Size([2, 3, 4])
X

Original shape: torch.Size([2, 3, 4])


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [25]:
X_permuted = X.permute(1, 0, 2)
print("Permuted shape:", X_permuted.shape)  # 输出：torch.Size([3, 2, 4])
X_permuted

Permuted shape: torch.Size([3, 2, 4])


tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])

In [26]:
# 4维张量
Y = torch.arange(120).reshape(2, 3, 4, 5)
print("Original shape:", Y.shape)  # 输出：torch.Size([2, 3, 4, 5])
Y

Original shape: torch.Size([2, 3, 4, 5])


tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])

In [27]:
Y1 = Y.permute(1, 0, 2, 3)
Y1

tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]]],


        [[[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]]],


        [[[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])

In [28]:
Y2 = Y.permute(0, 2, 1, 3)
Y2

tensor([[[[  0,   1,   2,   3,   4],
          [ 20,  21,  22,  23,  24],
          [ 40,  41,  42,  43,  44]],

         [[  5,   6,   7,   8,   9],
          [ 25,  26,  27,  28,  29],
          [ 45,  46,  47,  48,  49]],

         [[ 10,  11,  12,  13,  14],
          [ 30,  31,  32,  33,  34],
          [ 50,  51,  52,  53,  54]],

         [[ 15,  16,  17,  18,  19],
          [ 35,  36,  37,  38,  39],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 80,  81,  82,  83,  84],
          [100, 101, 102, 103, 104]],

         [[ 65,  66,  67,  68,  69],
          [ 85,  86,  87,  88,  89],
          [105, 106, 107, 108, 109]],

         [[ 70,  71,  72,  73,  74],
          [ 90,  91,  92,  93,  94],
          [110, 111, 112, 113, 114]],

         [[ 75,  76,  77,  78,  79],
          [ 95,  96,  97,  98,  99],
          [115, 116, 117, 118, 119]]]])