In [16]:
import torch.nn as nn
import torch

In [17]:
class SimpleModel(nn.Module):
    def __init__(self, input_dim):
        super(SimpleModel, self).__init__()
        self.fc = nn.Linear(input_dim, input_dim)
        self.layer_norm = nn.LayerNorm(input_dim)
    
    def forward(self, x):
        x = self.fc(x)
        x = self.layer_norm(x)
        return x

In [18]:
# 使用该模型
input_tensor = torch.randn(10, 5)  # 输入张量 (batch_size, num_features)
input_tensor

tensor([[ 0.3162, -2.2137, -1.5925, -0.2580, -1.5671],
        [ 0.3804, -1.0231, -1.2363, -0.1352,  1.6620],
        [-0.6123,  1.7899, -0.8963,  0.1565, -0.7575],
        [-0.2204, -0.5958,  1.0180, -1.0313,  0.2120],
        [-0.1593,  2.3156,  0.3629, -1.1718, -0.1657],
        [-0.4294,  0.5012, -1.0560, -1.4546, -0.9891],
        [-0.2447, -0.0641,  0.3572, -1.2087, -0.7265],
        [-0.0024, -1.1416, -0.2887, -0.0768, -0.4983],
        [ 1.3121,  0.5496, -0.3590, -0.0172,  0.3646],
        [ 0.4977,  0.5733,  0.0147,  0.8753,  0.3862]])

In [19]:
def layer_norm(x, epsilon=1e-5):
    # 计算每个样本特征维度的均值和标准差
    mean = x.mean(dim=-1, keepdim=True)         # (batch_size, ..., 1)
    std = x.std(dim=-1, keepdim=True)           # (batch_size, ..., 1)

    # 进行归一化
    x_normalized = (x - mean) / (std + epsilon)  # 加上 epsilon 防止除以零

    # 可选：引入可训练参数 gamma 和 beta（通常初始化为1和0）
    gamma = torch.ones(x.shape[-1])  # 与特征维度一致
    beta = torch.zeros(x.shape[-1])

    # 缩放和平移
    output = gamma * x_normalized + beta
    return output

In [20]:
print(layer_norm(input_tensor))

tensor([[ 1.3137, -1.0960, -0.5043,  0.7668, -0.4802],
        [ 0.3853, -0.8142, -0.9964, -0.0553,  1.4807],
        [-0.4924,  1.6648, -0.7475,  0.1979, -0.6228],
        [-0.1233, -0.6007,  1.4520, -1.1548,  0.4268],
        [-0.3070,  1.6138,  0.0982, -1.0929, -0.3121],
        [ 0.3382,  1.5669, -0.4891, -1.0152, -0.4007],
        [ 0.2189,  0.5171,  1.2124, -1.3721, -0.5763],
        [ 0.8738, -1.6201,  0.2471,  0.7110, -0.2118],
        [ 1.4890,  0.2838, -1.1522, -0.6120, -0.0086],
        [ 0.0905,  0.3328, -1.4563,  1.2996, -0.2666]])


In [21]:
model = SimpleModel(input_dim=5)
output = model(input_tensor)

In [22]:
print("Model Output with Layer Normalization:")
print(output)

Model Output with Layer Normalization:
tensor([[-1.3505,  1.0617, -0.5259, -0.4413,  1.2560],
        [-1.2754,  0.2045, -0.0734, -0.5836,  1.7279],
        [ 0.4182, -0.9553,  1.6191, -1.1350,  0.0530],
        [-0.3050,  0.9264, -1.8217,  0.6694,  0.5308],
        [ 1.5505, -0.9096,  0.7855, -0.9722, -0.4542],
        [ 0.6805,  0.0760,  1.3558, -1.5368, -0.5755],
        [ 0.7725,  1.2177, -1.6934, -0.0847, -0.2121],
        [-1.2332,  0.7179, -0.8581, -0.1146,  1.4880],
        [ 0.2347, -0.5737, -0.3939, -1.0813,  1.8142],
        [-0.2948, -0.8954,  0.1549, -0.8149,  1.8502]],
       grad_fn=<NativeLayerNormBackward0>)
