In [4]:
import numpy as np
from numpy.linalg import svd


In [ ]:
# 将矩阵定义为二维numpy数组
A = np.array([[4, 0], [3, -5]])

print("Original Vectors:")
print(A)

U, S, VT = svd(A)

print("Left Singular Vectors:")
print(U)

print("Singular Values:") 
print(np.diag(S))

print("Right Singular Vectors:") 
print(VT)

print(U @ np.diag(S) @ VT)


Left Singular Vectors:
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
Singular Values:
[[6.32455532 0.        ]
 [0.         3.16227766]]
Right Singular Vectors:
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]
[[ 4.00000000e+00 -1.11271234e-15]
 [ 3.00000000e+00 -5.00000000e+00]]
