In [1]:
import numpy as np

In [2]:
sizes = [2, 3, 1]
biases = [np.random.randn(y, 1) for y in sizes[1:]]

print(biases)
print(np.random.randn(3, 1))

[array([[-0.14464716],
       [-0.42529533],
       [-0.94405278]]), array([[-1.09044676]])]
[[-0.27493957]
 [ 2.53025915]
 [-0.38692732]]


In [3]:
array = np.array([1, 3, 7, 2, 5])
index = np.argmax(array)

print(index)

2


In [5]:
# 默认情况下，np.argmax(array) 会将数组展平成一维数组，然后返回最大值的索引。
array = np.array([[1, 3, 7], [2, 5, 6]])
print(array)
index = np.argmax(array)

print(index)  # Output: 2

[[1 3 7]
 [2 5 6]]
2


In [7]:
# 在这个例子中，np.argmax(array, axis=0) 返回沿着轴0（即每列）查找的最大值的索引。
array = np.array([[1, 3, 7], [2, 5, 6]])
print(array)
index = np.argmax(array, axis=0)

print(index)  # Output: [1 1 0]

[[1 3 7]
 [2 5 6]]
[1 1 0]


In [9]:
index = np.argmax(array, axis=1)

print(index)

[2 2]
