In [1]:
import torch
import torch.nn as nn

# 定义一个简单的全连接层
fc = nn.Linear(10, 5)  # 输入特征维度为 10，输出维度为 5

# 输入数据
input_data = torch.randn(3, 10)  # 3 个样本，每个样本 10 个特征

# 前向传播
output = fc(input_data)
print("Output shape:", output.shape)
print("Output data:", output)

Output shape: torch.Size([3, 5])
Output data: tensor([[ 0.9457, -0.7943, -0.7703, -0.4567,  0.9799],
        [ 0.4156,  0.4461, -0.4889,  0.5330,  0.3456],
        [-0.0777, -0.4175, -0.6112,  1.0478, -0.1331]],
       grad_fn=<AddmmBackward0>)


nn.Linear的初始化是kaiming初始化，权重随机，并且服从kaiming正态分布，或者kaiming均匀分布。

In [ ]:
# 查看权重
print("Weights shape:", fc.weight.shape)
print("Weights:", fc.weight)

# 查看偏置
print("Bias shape:", fc.bias.shape)
print("Bias:", fc.bias)

Weights shape: torch.Size([5, 10])
Weights: Parameter containing:
tensor([[ 0.0975, -0.0423,  0.0851, -0.2376,  0.1699, -0.1101,  0.2944, -0.0440,
         -0.2503, -0.1867],
        [ 0.1927, -0.0534, -0.2468, -0.2163, -0.0210,  0.2709,  0.1510, -0.1738,
         -0.1391,  0.2945],
        [-0.1978, -0.2784, -0.0853,  0.2564, -0.2789,  0.1321, -0.0860, -0.2420,
         -0.0260,  0.0207],
        [ 0.2019,  0.2552,  0.3058,  0.0708,  0.0423, -0.1513, -0.1126, -0.0308,
          0.2653, -0.0245],
        [-0.0620, -0.2037,  0.0298,  0.2274,  0.1903,  0.2558,  0.2384,  0.1050,
         -0.0588, -0.1368]], requires_grad=True)
Bias shape: torch.Size([5])
Bias: Parameter containing:
tensor([ 0.2637,  0.1778, -0.1278,  0.1444,  0.0725], requires_grad=True)


In [ ]:
import torch.nn.init as init

# 创建一个权重张量
weight_tensor = torch.empty(3, 5)  # 假设输出维度为 3，输入维度为 5

# mode：可以是 'fan_in' 或 'fan_out'。'fan_in' 用于正向传播，'fan_out' 用于反向传播。
# nonlinearity：指定激活函数，通常为 'relu' 或 'leaky_relu'。

# 使用 Kaiming Normal 初始化
init.kaiming_normal_(weight_tensor, mode='fan_in', nonlinearity='relu')

tensor([[ 0.2426,  0.6685,  0.2791, -0.7569,  0.8786],
        [-0.5745,  0.4410,  0.6357,  0.5542,  1.1811],
        [-0.6354, -0.7361,  0.4808, -0.5053,  0.6695]])

In [5]:
# 使用 Kaiming Uniform 初始化
init.kaiming_uniform_(weight_tensor, mode='fan_in', nonlinearity='relu')

tensor([[ 0.4350,  0.9396,  0.3711,  0.0638, -0.3164],
        [-0.2429, -0.0604,  0.4859, -1.0709, -0.8706],
        [-0.9281, -0.4747,  0.8582, -0.9444,  0.9820]])